name: Pipeline-build-and-deploy-BE

on:
 push:
    branches:
      - EXP-38_pipeline_build_and_deploy_BE

env:
  RG_NAME: apprenticeship-expenses-manager-rg
  VM_NAME: exp-vm-backend
  
jobs:
  Build_and_Deploy:
   runs-on: ubuntu-latest
   steps:
   - name: Checkout Repository
     uses: actions/checkout@v2
   - name: Set up Java
     uses: actions/setup-java@v2
     with:
       distribution: 'adopt'
       java-version: '17'
   - name: Install Maven
     uses: stCarolas/setup-maven@v4.5
     with:
        maven-version: 3.9.5 #incercam cu versiunea 3.9.5 momentan deoarece 4.0.0 nu e disponibila 
       
   - name: Build
     run: mvn clean package -DskipTests=true
   
   - name: 'Create a temporary key file'
     run: |
      sudo echo "${{ secrets.BE_PRIVATE_SSH_KEY }}" > temp_key.pem
      chmod 600 temp_key.pem

   - name: Check Azure CLI Version
     run: az --version

   - name: Log in with Azure
     uses: azure/login@v1
     with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'  
        
   - name: Get Azure VM IP Address
     id: get_ip
     run: |
        echo "VM_IP=$(az vm show -d --resource-group $RG_NAME --name $VM_NAME --query publicIps -o tsv)" >> "$GITHUB_OUTPUT"
     
   - name: SSH into VM
     run: |
       ssh -i temp_key.pem -o StrictHostKeyChecking=no azureuser@${{ steps.get_ip.outputs.VM_IP }} 'bash -s' << 'ENDSSH'
       sudo apt-get update
       sudo apt install openjdk-17-jre-headless
       # sudo mkdir be_expenses_manager
       #cd be_expenses_manager
       ls
       sudo chown -R $USER:$USER be_expenses_manager
       ENDSSH
 
   - name: Copy in VM
     run: |
      scp -i temp_key.pem -r ./target/* azureuser@${{ steps.get_ip.outputs.VM_IP }}:be_expenses_manager

   - name: Run Java aplication on VM
     run: |
        ssh -i temp_key.pem -o StrictHostKeyChecking=no azureuser@${{ steps.get_ip.outputs.VM_IP }} 'bash -s' << 'ENDSSH'
        java -jar be_expenses_manager/target/expenses-manager-0.0.1-SNAPSHOT.jar
        ENDSSH
   
   - name: Clean up temporary key file
     run: sudo rm temp_key.pem
