name: Pipeline-build-and-deploy-BE

on:
 push:
    branches:
      - EXP-38_pipeline_build_and_deploy_BE
jobs:
  Build_and_Deploy:
   runs-on: ubuntu-latest
   steps:
   - name: Checkout Repository
     uses: actions/checkout@v2
   - name: Set up Java
     uses: actions/setup-java@v2
     with:
       distribution: 'adopt'
       java-version: '17'
   - name: Install Maven
     uses: stCarolas/setup-maven@v4.5
     with:
        maven-version: 3.9.5 #incercam cu versiunea 3.9.5 momentan deoarece 4.0.0 nu e disponibila 
       
   - name: Build
     run: mvn clean package -DskipTests=true
   
   - name: 'Create a temporary key file'
     run: |
      sudo echo "${{ secrets.BE_PRIVATE_SSH_KEY }}" > temp_key.pem
      chmod 600 temp_key.pem

   - name: SSH into VM
     run: |
       ls -l temp_key.pem
       ssh -i temp_key.pem -o StrictHostKeyChecking=no azureuser@20.73.89.17 'bash -s' << 'ENDSSH'
       sudo apt-get update
       sudo mkdir be_expenses_manager
       ls
       cd be_expenses_manager
       ENDSSH
   - name: Copy in VM
     run: |
      scp ssh -i D:/devopsp/git/vmback_ssh_key -r D:/devopsp/git/be_expenses_manager/target azureuser@20.73.89.17:/
   - name: Run Java aplication on VM
     run: java -jar be_expenses_manager/target/expenses-manager-0.0.1-SNAPSHOT.jar
   - name: Clean up temporary key file
     run: |
      rm temp_key.pem
