name: Build and Deploy BE

on: workflow_dispatch 
  
env:
  RG_NAME: apprenticeship-expenses-manager-rg
  VM_NAME: exp-vm-backend
  DB_USERNAME: ${{ secrets.TF_ADMIN_USERNAME }}
  DB_PASSWORD: ${{ secrets.TF_ADMIN_PASSWORD }}
  DB_URL: ${{ secrets.TF_MYSQL_JDBC }}
  REPORTS_ST_SAS_TOKEN_URL: ${{ secrets.REPORTS_ST_SAS_TOKEN_URL }}
  
jobs:
  Build_and_Deploy:
   runs-on: ubuntu-latest
   timeout-minutes: 5
   steps:
   - name: Checkout Repository
     uses: actions/checkout@v2
   - name: Set up Java
     uses: actions/setup-java@v2
     with:
      distribution: 'adopt'
      java-version: '17'
   - name: Install Maven
     uses: stCarolas/setup-maven@v4.5
     with:
      maven-version: 3.9.5 #incercam cu versiunea 3.9.5 momentan deoarece 4.0.0 nu e disponibila 
       
   - name: Build
     run: mvn clean package '-DskipTests=true' 

   - name: 'Create a temporary key file'
     run: |
       sudo echo "${{ secrets.BE_PRIVATE_SSH_KEY }}" > temp_key.pem
       chmod 600 temp_key.pem

   - name: Check Azure CLI Version
     run: az --version

   - name: Log in with Azure
     uses: azure/login@v1
     with:
      creds: '${{ secrets.AZURE_CREDENTIALS }}'  
        
   - name: Get Azure VM IP Address
     id: get_ip
     run: |
       echo "VM_IP=$(az vm show -d --resource-group $RG_NAME --name $VM_NAME --query publicIps -o tsv)" >> "$GITHUB_OUTPUT"
     
   - name: SSH into VM
     run: |
       ssh -i temp_key.pem -o StrictHostKeyChecking=no azureuser@${{ steps.get_ip.outputs.VM_IP }} 'bash -s' << 'ENDSSH'
       sudo apt-get update
       sudo apt install -y openjdk-17-jre-headless
       sudo mkdir be_expenses_manager
       sudo chown -R $USER:$USER be_expenses_manager
       ENDSSH
 
   - name: Run Java aplication on VM
     run: |
       scp -i temp_key.pem -r ./target/*.jar azureuser@${{ steps.get_ip.outputs.VM_IP }}:be_expenses_manager
       ssh -i temp_key.pem -o StrictHostKeyChecking=no azureuser@${{ steps.get_ip.outputs.VM_IP }} 'bash -s' << 'ENDSSH'
       if [ -n $(pgrep -f 'java') ]; then kill $(pgrep -f 'java'); fi
       cd be_expenses_manager
       nohup java -Dspring.datasource.username="${{ env.DB_USERNAME }}" -Dspring.datasource.password="${{ env.DB_PASSWORD }}" -Dspring.datasource.url="${{ env.DB_URL }}" -Dazure.document.blob.connectionString="${{ env.REPORTS_ST_SAS_TOKEN_URL }}" -jar expenses-manager-0.0.1-SNAPSHOT.jar > nohup.out  2>&1 &
       sleep 30
       if [ -n $(pgrep -f 'java') ]; then echo "Java start successfully"; else echo "Java faild to start" && exit 1; fi
       ENDSSH
